### ISSUE TITLE
Failing to Sign TX with Ledger  X

### ISSUE THREAD

**Issue by CryptoCloaks** [btcpayserver/BTCPayServer.Vault#23]
Currently having issues signing tx to broadcast on the Ledger X

I have the latest version of 
- BTCPAYServer
- Vault
- Ledger Bitcoin App
- Ledger Firmware

**More info**
- Trying to combine 13 utxos - Doesn't work
- When manually selecting just one UTXO to try and send that allows me to broadcast
- Tried combining just two. Confirmed on the ledger and then the next screen just has view PSBT no broadcast button.

Currently the process gets stuck after I confirm that transactions on the Ledger itself.

BTC Vault just sits at sign TX and does not continue to the point where I can click Broadcast.

Have discussed issue on matter with Brittttttk she was successful on S, did not have an X to try.

Trying to combine:
![Image Pasted at 2020-10-11 16-35](https://user-images.githubusercontent.com/40768388/95690807-e9058e00-0bdf-11eb-9b26-668b82f12357.png)

Sending just a single:
![Image Pasted at 2020-10-11 16-39](https://user-images.githubusercontent.com/40768388/95690882-7fd24a80-0be0-11eb-8875-dba1ced5ea5a.png)

**Comment by NicolasDorier** [comment]
As discussed in the chat, you need to check off the box

![image](https://user-images.githubusercontent.com/3020646/95859054-fb76f780-0d98-11eb-8a78-606017cfed51.png)

"Always include non-witness UTXO if available"

We now set that to true by default to fix the segwit fee bug and to match bitcoin core behavior.
However, since it seems some wallet don't support it properly, we will revert this decision in next release.

**Comment by NicolasDorier** [comment]
Can you try on the latest version of HWI? it may have fixed it.
